[dependencies]
assimulo = ">=3.5.2"
python = ">=3.12.0,<3.13"
pip = ">=24.3.1,<25"
ipykernel = ">=6.29.5,<7"
notebook = ">=7.2.2,<8"
pytest = ">=8.4.1,<9"
pytest-cov = ">=6.2.1,<7"

[pypi-dependencies]
mxlbricks = {path = ".", editable = true}

[target.osx-arm64.dependencies]
clang = "*"

[target.win-64.dependencies]
posix = ">=1.0.0,<2"

[tasks]
test = {cmd = ["pytest", "tests"]}
test-cov = {cmd = ["pytest", "--disable-warnings", "--cov", "--cov-report", "json", "tests"]}

[workspace]
authors = ["Marvin van Aalst <marvin.vanaalst@gmail.com>"]
channels = ["conda-forge"]
name = "mxl-bricks"
platforms = ["linux-64", "win-64", "osx-arm64"]
version = "0.1.0"
